const SAFE_CODES = new Set([
  'BODY_TOO_LARGE', 'CONTEXT_BUDGET_EXCEEDED', 'CONTEXT_SOURCE_UNAVAILABLE', 'CREATE_FAILED',
  'CREW_RECOVERY_REQUIRED', 'CWD_LEASE_CONFLICT', 'CWD_NOT_DIRECTORY', 'CWD_NOT_FOUND',
  'CWD_UNREADABLE', 'DELIVERY_RETRY_REQUIRED', 'EMPLOYEE_NOT_FOUND', 'EMPLOYEE_RUNTIME_EXITED',
  'EMPLOYEE_START_FAILED', 'FORBIDDEN', 'FORGED_SERVER_FIELD', 'IDEMPOTENCY_CONFLICT',
  'INTERNAL_ERROR', 'INVALID_BODY', 'INVALID_INPUT', 'INVALID_INTENT', 'INVALID_MESSAGE',
  'INVALID_MUTATION_ID', 'INVALID_TRANSITION', 'MODEL_UNSUPPORTED', 'MUTATION_OUTCOME_UNKNOWN',
  'MUTATION_PENDING', 'NOT_FOUND', 'ORG_NOT_FOUND', 'PATH_UNAVAILABLE', 'PATH_UNREADABLE',
  'POLICY_REJECTED', 'PROMOTION_FAILED', 'RECOVERY_REQUIRED', 'REGISTRY_CORRUPT',
  'RESUME_HANDLE_MISSING', 'RESUME_HANDLE_UNAVAILABLE', 'RUNTIME_REQUEST_REJECTED',
  'RUNTIME_START_FAILED', 'SANDBOX_UNAVAILABLE', 'STALE_PROPOSAL', 'UNAUTHENTICATED',
]);

export function publicApplicationError(code: unknown, fallback = 'INTERNAL_ERROR'): { code: string; status: number } {
  const safe = typeof code === 'string' && SAFE_CODES.has(code) ? code : fallback;
  if (safe === 'BODY_TOO_LARGE' || safe === 'CONTEXT_BUDGET_EXCEEDED') return { code: safe, status: 413 };
  if (['NOT_FOUND', 'CWD_NOT_FOUND', 'EMPLOYEE_NOT_FOUND', 'ORG_NOT_FOUND', 'PATH_UNAVAILABLE', 'PATH_UNREADABLE'].includes(safe)) return { code: safe, status: 404 };
  if (safe === 'UNAUTHENTICATED') return { code: safe, status: 401 };
  if (safe === 'FORBIDDEN') return { code: safe, status: 403 };
  if (['IDEMPOTENCY_CONFLICT', 'CWD_LEASE_CONFLICT', 'INVALID_TRANSITION', 'RESUME_HANDLE_MISSING', 'STALE_PROPOSAL'].includes(safe)) return { code: safe, status: 409 };
  if (['REGISTRY_CORRUPT', 'RECOVERY_REQUIRED', 'MUTATION_PENDING', 'CREW_RECOVERY_REQUIRED', 'MUTATION_OUTCOME_UNKNOWN', 'CONTEXT_SOURCE_UNAVAILABLE'].includes(safe)) return { code: safe, status: 503 };
  if (safe.endsWith('_FAILED') || ['INTERNAL_ERROR', 'MODEL_UNSUPPORTED', 'POLICY_REJECTED', 'SANDBOX_UNAVAILABLE', 'RUNTIME_REQUEST_REJECTED', 'RESUME_HANDLE_UNAVAILABLE'].includes(safe)) return { code: safe, status: 500 };
  return { code: safe, status: 400 };
}
